### ISSUE TITLE
Rstudio crashes if the length of cutpoints is less than the number of effect modifiers

### ISSUE THREAD

**Issue by EoghanONeill** [skdeshpande91/VCBART#4]
I think an error message should be added to note that the length of the cutpoints list must equal the number of effect modifiers. Otherwise R crashes on line 135 of vcbart_ind_adapt_split.cpp if the length of cutpoints is less than the number of effect modifiers.

````
for(size_t r = 0; r < R; r++){
    Rcpp::NumericVector tmp = xinfo_list[r];
    std::vector<double> tmp2;
    for(int rr = 0; rr < tmp.size(); rr++) tmp2.push_back(tmp[rr]);
    xi[r] = tmp2;
  }
````

**Comment by skdeshpande91** [comment]
Thanks for catching this! 
We've added a [check ](https://github.com/skdeshpande91/VCBART/blob/master/VCBART/R/VCBART.R#L87-L88) to the main function `VCBART()`
